name: Verible formatter example

on:
  push:
    branches: [ ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-formatter-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
